In [2]:
%pip install matplotlib

Requirement already satisfied: matplotlib in ./.venv/lib/python3.13/site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('outlier_loudness.csv' , sep = ';')
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5.176,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...
1,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5.176,0.033,0.483,0.000,0.834,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...
2,2,WHERE SHE GOES,Bad Bunny,29/05/2023,0.652,0.800,-4.019,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5.678,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...
4,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5.678,0.333,0.213,0.000,0.559,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...

In [5]:
df.to_csv('outlier_loudness.csv', index=False, sep =';')

### Cleaning duplicated row

#### Check same 'Rank','Title','Date' in each day
We found out there are several rows that are duplicated , but they are different in how they manage artist for example

In [6]:
df[(df['Title'] == 'Better Days (NEIKED x Mae Muller x Polo G)') & (df['Date'] == '08/01/2022') & (df['Artist (Ind.)'] == 'Polo G')]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
129465,87,Better Days (NEIKED x Mae Muller x Polo G),NEIKED,08/01/2022,0.717,0.671,-5.077,0.034,0.002,0.0,0.699,Artist 3,Polo G,Nationality 3,United States,Anglo-America,114,38.0,6f5ExP43esnvdKPddwKXJH,https://open.spotify.com/track/6f5ExP43esnvdKP...
129468,87,Better Days (NEIKED x Mae Muller x Polo G),"NEIKED, Mae Muller, Polo G",08/01/2022,0.717,0.671,-5.077,0.034,0.002,0.0,0.699,Artist 3,Polo G,Nationality 3,United States,Anglo-America,114,38.0,6f5ExP43esnvdKPddwKXJH,https://open.spotify.com/track/6f5ExP43esnvdKP...

In [7]:
df_dup = df.duplicated(subset=['Rank','Title','Date'] , keep = False)
df[df_dup][['Rank','Title','Date']].value_counts()

Rank  Title            Date
87    Quizás           24/09/2019    9
86    Quizás           25/09/2019    9
97    Bande organisée  05/09/2020    9
136   Bande organisée  28/09/2020    9
117   Bande organisée  30/09/2020    9
                                    ..
72    Robarte un Beso  26/11/2017    2
                       23/11/2017    2
                       20/09/2017    2
                       18/10/2017    2
200   Échame La Culpa  22/08/2018    2
Name: count, Length: 127129, dtype: int64

In [8]:
df_dup = df.duplicated(subset=['Rank','Title','Date'] , keep = False)
df[df_dup][['Rank','Title','Date','id']]

        Rank             Title        Date                      id
0          1   Ella Baila Sola  29/05/2023  3qQbCzHBycnDpGskqOWY0E
1          1   Ella Baila Sola  29/05/2023  3qQbCzHBycnDpGskqOWY0E
3          3   La Bebe - Remix  29/05/2023  2UW7JaomAMuX9pZrjVpHAU
4          3   La Bebe - Remix  29/05/2023  2UW7JaomAMuX9pZrjVpHAU
6          5         un x100to  29/05/2023  6pD0ufEQq0xdHSsRbg9LBK
...      ...               ...         ...                     ...
651918    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651919    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651920    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651924    72  X (feat. Future)  01/01/2017  6fwdbPMwP1zVStm8FybmkO
651925    72  X (feat. Future)  01/01/2017  6fwdbPMwP1zVStm8FybmkO

[310310 rows x 4 columns]

In [9]:
df_new = df.copy()
df_new1 = df_new[['Rank','Title','Artists','Date','Danceability','Energy','Loudness','Speechiness','Acousticness','Instrumentalness','Valence','id']]
df_new1.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,id
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5.176,0.033,0.483,0.000,0.834,3qQbCzHBycnDpGskqOWY0E
1,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5.176,0.033,0.483,0.000,0.834,3qQbCzHBycnDpGskqOWY0E
2,2,WHERE SHE GOES,Bad Bunny,29/05/2023,0.652,0.800,-4.019,0.061,0.143,0.629,0.234,7ro0hRteUMfnOioTFI5TG1
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5.678,0.333,0.213,0.000,0.559,2UW7JaomAMuX9pZrjVpHAU
4,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5.678,0.333,0.213,0.000,0.559,2UW7JaomAMuX9pZrjVpHAU

In [10]:
df_dup = df_new.duplicated(subset=['Rank','Title','Date'] , keep = False)
df[df_dup][['Rank','Title','Date','id']]

        Rank             Title        Date                      id
0          1   Ella Baila Sola  29/05/2023  3qQbCzHBycnDpGskqOWY0E
1          1   Ella Baila Sola  29/05/2023  3qQbCzHBycnDpGskqOWY0E
3          3   La Bebe - Remix  29/05/2023  2UW7JaomAMuX9pZrjVpHAU
4          3   La Bebe - Remix  29/05/2023  2UW7JaomAMuX9pZrjVpHAU
6          5         un x100to  29/05/2023  6pD0ufEQq0xdHSsRbg9LBK
...      ...               ...         ...                     ...
651918    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651919    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651920    24          Starving  01/01/2017  1qOLh0tI7trd1zdDKxYZTe
651924    72  X (feat. Future)  01/01/2017  6fwdbPMwP1zVStm8FybmkO
651925    72  X (feat. Future)  01/01/2017  6fwdbPMwP1zVStm8FybmkO

[310310 rows x 4 columns]

In [11]:
df_clean = df_new.drop_duplicates(subset=['Rank', 'Title', 'Date'], keep='first').copy()
print("Before delete duplicated row: ", df.shape[0])
print("After delete duplicated row: ", df_clean.shape[0])

Before delete duplicated row:  651936
After delete duplicated row:  468755

- Check same Rank in each day

In [12]:
df_clean[df_clean.duplicated(subset=['Rank','id','Date'] , keep = False)]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
7905,199,Lose Yourself,Eminem,28/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,2,2.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
7906,199,"Lose Yourself - From ""8 Mile"" Soundtrack",Eminem,28/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,2,2.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8160,191,Lose Yourself,Eminem,27/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,10,10.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8161,191,"Lose Yourself - From ""8 Mile"" Soundtrack",Eminem,27/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,10,10.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8413,187,Lose Yourself,Eminem,26/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,14,14.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586725,47,This Is What You Came For (feat. Rihanna),Calvin Harris,03/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,154,154.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
586961,46,This Is What You Came For,Calvin Harris Rihanna,02/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,155,155.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
586962,46,This Is What You Came For (feat. Rihanna),Calvin Harris,02/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,155,155.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
587036,34,This Is What You Came For,Calvin Harris Rihanna,01/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,167,167.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
587037,34,This Is What You Came For (feat. Rihanna),Calvin Harris,01/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,167,167.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...

In [13]:
df_clean[df_clean.duplicated(subset=['Rank','Date'], keep=False)]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
7905,199,Lose Yourself,Eminem,28/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,2,2.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
7906,199,"Lose Yourself - From ""8 Mile"" Soundtrack",Eminem,28/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,2,2.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8160,191,Lose Yourself,Eminem,27/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,10,10.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8161,191,"Lose Yourself - From ""8 Mile"" Soundtrack",Eminem,27/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,10,10.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
8413,187,Lose Yourself,Eminem,26/04/2023,0.686,0.735,-4.616,0.264,0.009,0.001,0.060,Artist 1,Eminem,Nationality 1,United States,Anglo-America,14,14.0,1v7L65Lzy0j0vdpRjJewt1,https://open.spotify.com/track/1v7L65Lzy0j0vdp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586725,47,This Is What You Came For (feat. Rihanna),Calvin Harris,03/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,154,154.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
586961,46,This Is What You Came For,Calvin Harris Rihanna,02/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,155,155.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
586962,46,This Is What You Came For (feat. Rihanna),Calvin Harris,02/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,155,155.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
587036,34,This Is What You Came For,Calvin Harris Rihanna,01/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,167,167.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...
587037,34,This Is What You Came For (feat. Rihanna),Calvin Harris,01/01/2017,0.631,0.927,-2.787,0.033,0.199,0.119,0.465,Artist 1,Calvin Harris,Nationality 1,United Kingdom,Europe,167,167.0,0azC730Exh71aQlOt9Zj3y,https://open.spotify.com/track/0azC730Exh71aQl...

In [14]:
print(df_clean[df_clean.duplicated(subset=['Rank','Date'], keep=False)][['Rank','Date']].value_counts())
print("Number of ducplicated row :",df_clean[df_clean.duplicated(subset=['Rank','Date'], keep=False)][['Rank','Date']].shape[0])

Rank  Date
17    25/06/2021    2
166   20/08/2022    2
167   26/01/2023    2
      24/02/2022    2
      23/11/2021    2
                   ..
125   10/04/2022    2
      01/05/2022    2
124   19/03/2022    2
      18/03/2022    2
200   27/07/2022    2
Name: count, Length: 1685, dtype: int64
Number of ducplicated row : 3370

In [15]:
df_clean[df_clean.duplicated(subset=['Rank','Date'], keep=False)][['Rank','Title','Date','id']]

,Rank,Title,Date,id
7905,199,Lose Yourself,28/04/2023,1v7L65Lzy0j0vdpRjJewt1
7906,199,"Lose Yourself - From ""8 Mile"" Soundtrack",28/04/2023,1v7L65Lzy0j0vdpRjJewt1
8160,191,Lose Yourself,27/04/2023,1v7L65Lzy0j0vdpRjJewt1
8161,191,"Lose Yourself - From ""8 Mile"" Soundtrack",27/04/2023,1v7L65Lzy0j0vdpRjJewt1
8413,187,Lose Yourself,26/04/2023,1v7L65Lzy0j0vdpRjJewt1
...,...,...,...,...
586725,47,This Is What You Came For (feat. Rihanna),03/01/2017,0azC730Exh71aQlOt9Zj3y
586961,46,This Is What You Came For,02/01/2017,0azC730Exh71aQlOt9Zj3y
586962,46,This Is What You Came For (feat. Rihanna),02/01/2017,0azC730Exh71aQlOt9Zj3y
587036,34,This Is What You Came For,01/01/2017,0azC730Exh71aQlOt9Zj3y
587037,34,This Is What You Came For (feat. Rihanna),01/01/2017,0azC730Exh71aQlOt9Zj3y

In [16]:
df_clean_same_rank_in_each_date = df_clean.drop_duplicates(subset=['Rank','Date'], keep='first').copy()
print("Before delete duplicated row: ", df.shape[0])
print("After delete duplicated row(Title,Date,Rank): ", df_clean.shape[0])
print("After delete duplicated row (Date,Rank) :", df_clean_same_rank_in_each_date.shape[0])

Before delete duplicated row:  651936
After delete duplicated row(Title,Date,Rank):  468755
After delete duplicated row (Date,Rank) : 467070

- Check different rank in the same date

In [17]:
df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date'], keep=False)]
print(df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date'], keep=False)].shape[0])
print(df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['Title','Date'], keep=False)].shape[0])

18
2640

In [18]:
print(df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date','Title'], keep=False)].shape)
df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date','Title'], keep=False)]

(18, 20)

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
23936,3,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",21/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,198,99.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
23938,196,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",21/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,5,5.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26051,5,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",12/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,196,98.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26053,173,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",12/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,28,28.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26299,7,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",11/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,194,97.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26301,182,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",11/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,19,19.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26540,7,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",10/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,194,97.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26542,163,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",10/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,38,38.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26778,12,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",09/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,189,94.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
26780,108,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",09/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,93,93.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27024,18,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",08/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,183,92.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27026,101,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",08/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,100,100.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27278,29,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",07/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,172,86.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27280,98,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",07/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,103,103.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27529,62,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",06/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,139,70.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27531,112,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",06/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,89,89.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27785,115,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",05/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,86,43.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...
27787,117,Boy's a liar Pt. 2,"PinkPantheress, Ice Spice",05/02/2023,0.696,0.809,-8.254,0.05,0.252,0.0,0.857,Artist 1,PinkPantheress,Nationality 1,United Kingdom,Europe,84,84.0,6AQbmUe0Qwf5PZnt4HmTXv,https://open.spotify.com/track/6AQbmUe0Qwf5PZn...

In [19]:
print(df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date',], keep=False)].shape)
df_clean_same_rank_in_each_date[df_clean_same_rank_in_each_date.duplicated(subset=['id','Date',], keep=False)][['id','Date','Rank']].value_counts()

(18, 20)

id                      Date        Rank
6AQbmUe0Qwf5PZnt4HmTXv  05/02/2023  115     1
                                    117     1
                        21/02/2023  3       1
                        12/02/2023  173     1
                                    5       1
                        11/02/2023  182     1
                                    7       1
                        10/02/2023  163     1
                                    7       1
                        09/02/2023  108     1
                                    12      1
                        08/02/2023  101     1
                                    18      1
                        07/02/2023  98      1
                                    29      1
                        06/02/2023  112     1
                                    62      1
                        21/02/2023  196     1
Name: count, dtype: int64

- We decided to keep last

In [20]:
df_clean_final = df_clean_same_rank_in_each_date.drop_duplicates(subset=['id','Date'], keep='last').copy()
print(df_clean_final.shape[0])

467061

- We also find out that there are many songs that have different id but it show the same title, we analyze and found out there are from different location (album , single). So, we decided to keep it

In [21]:
df_clean_final[df_clean_final.duplicated(subset=['Title','Date','Artists'], keep=False)]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
11370,21,Chemical,Post Malone,14/04/2023,0.498,0.897,-4.907,0.045,0.001,0.000,0.373,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,180,180.0,5w40ZYhbBMAlHYNDaVJIUu,https://open.spotify.com/track/5w40ZYhbBMAlHYN...
11371,173,Chemical,Post Malone,14/04/2023,0.480,0.895,-4.872,0.043,0.002,0.000,0.356,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,28,28.0,4qzEjmuz380jeiBJp31oDY,https://open.spotify.com/track/4qzEjmuz380jeiB...
38392,2,Rockin' Around The Christmas Tree,Brenda Lee,25/12/2022,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,199,199.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
38393,156,Rockin' Around The Christmas Tree,Brenda Lee,25/12/2022,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,45,45.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
38631,3,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2022,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
38632,108,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2022,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,93,93.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
128211,188,Take My Breath,The Weeknd,13/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,13,13.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
128212,51,Take My Breath,The Weeknd,13/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,150,150.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
128504,180,Take My Breath,The Weeknd,12/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,21,21.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
128505,38,Take My Breath,The Weeknd,12/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,163,163.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
128799,171,Take My Breath,The Weeknd,11/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,30,30.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
128800,28,Take My Breath,The Weeknd,11/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,173,173.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
129095,160,Take My Breath,The Weeknd,10/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,41,41.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
129096,23,Take My Breath,The Weeknd,10/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,178,178.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
129386,186,Take My Breath,The Weeknd,09/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,15,15.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
129387,20,Take My Breath,The Weeknd,09/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,181,181.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
129683,157,Take My Breath,The Weeknd,08/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,44,44.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
129684,16,Take My Breath,The Weeknd,08/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,185,185.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...
129976,151,Take My Breath,The Weeknd,07/01/2022,0.747,0.739,-6.008,0.049,0.011,0.000,0.523,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,50,50.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...
129977,13,Take My Breath,The Weeknd,07/01/2022,0.698,0.769,-7.154,0.037,0.013,0.002,0.354,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,188,188.0,0XvDZGVqGYM7P4rgzRnWhq,https://open.spotify.com/track/0XvDZGVqGYM7P4r...
133796,3,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2021,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
133981,164,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2021,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,37,37.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
188567,18,9 5 . s o u t h,J. Cole,14/05/2021,0.713,0.793,-5.277,0.397,0.271,0.000,0.203,Artist 1,J. Cole,Nationality 1,United States,Anglo-America,183,183.0,5R691ipUYRDYW6ehapjoj6,https://open.spotify.com/track/5R691ipUYRDYW6e...
222058,3,Rockin' Around The Christmas Tree,Brenda Lee,25/12/2020,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
222059,185,Rockin' Around The Christmas Tree,Brenda Lee,25/12/2020,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,16,16.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
222295,6,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2020,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,195,195.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
222296,132,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2020,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,69,69.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
310160,7,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2019,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,194,194.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
310161,153,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2019,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,48,48.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
406144,7,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2018,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,194,194.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
406145,151,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2018,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,50,50.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
453591,109,the light is coming (feat. Nicki Minaj),Ariana Grande,20/06/2018,0.879,0.544,-5.667,0.151,0.015,0.000,0.670,Artist 1,Ariana Grande,Nationality 1,United States,Anglo-America,92,92.0,5iZ4hcpCgFVijq5OOjBTKZ,https://open.spotify.com/track/5iZ4hcpCgFVijq5...
484988,20,Amorfoda,Bad Bunny,20/02/2018,0.742,0.432,-7.539,0.062,0.984,0.000,0.252,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,181,181.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...
484989,162,Amorfoda,Bad Bunny,20/02/2018,0.616,0.587,-6.439,0.091,0.978,0.006,0.279,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,39,39.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...
485253,29,Amorfoda,Bad Bunny,19/02/2018,0.742,0.432,-7.539,0.062,0.984,0.000,0.252,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,172,172.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...
485254,106,Amorfoda,Bad Bunny,19/02/2018,0.616,0.587,-6.439,0.091,0.978,0.006,0.279,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,95,95.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...
485521,37,Amorfoda,Bad Bunny,18/02/2018,0.742,0.432,-7.539,0.062,0.984,0.000,0.252,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,164,164.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...
485522,106,Amorfoda,Bad Bunny,18/02/2018,0.616,0.587,-6.439,0.091,0.978,0.006,0.279,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,95,95.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...
500948,11,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2017,0.589,0.472,-8.749,0.050,0.614,0.000,0.898,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,190,190.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...
500950,158,Rockin' Around The Christmas Tree,Brenda Lee,24/12/2017,0.682,0.641,-8.915,0.039,0.568,0.000,0.826,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,43,43.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...
612056,19,9 5 . s o u t h,J. Cole,14/05/2021,0.622,0.794,-4.450,0.438,0.228,0.000,0.216,Artist 1,J. Cole,Nationality 1,United States,Anglo-America,182,182.0,4GSBObGq3DuiKFlytKBbEw,https://open.spotify.com/track/4GSBObGq3DuiKFl...
623962,2,Toosie Slide,Drake,03/04/2020,0.834,0.454,-9.750,0.201,0.321,0.000,0.837,Artist 1,Drake,Nationality 1,Canada,Anglo-America,199,199.0,127QTOFJsJQp5LbJbu3A1y,https://open.spotify.com/track/127QTOFJsJQp5Lb...
623963,138,Toosie Slide,Drake,03/04/2020,0.832,0.431,-9.810,0.197,0.344,0.000,0.847,Artist 1,Drake,Nationality 1,Canada,Anglo-America,63,63.0,1d2eMMrAuIsw85u3YklKoc,https://open.spotify.com/track/1d2eMMrAuIsw85u...
640265,197,the light is coming (feat. Nicki Minaj),Ariana Grande,20/06/2018,0.879,0.547,-5.670,0.148,0.015,0.000,0.665,Artist 1,Ariana Grande,Nationality 1,United States,Anglo-America,4,4.0,397Un0hOSVgAdLcIHpGAxp,https://open.spotify.com/track/397Un0hOSVgAdLc...

- We also check about song that are different but have the same value in music variables. However, we decided to keep all of them because they are different.

In [22]:
df_clean_final[df_clean_final.duplicated(subset=['Date','Danceability','Energy','Loudness','Speechiness','Acousticness','Instrumentalness','Valence'], keep=False)]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
18356,145,Peso a Peso,"Eladio Carrion, Quavo, Rich The Kid, Ñengo Flow",17/03/2023,0.469,0.639,-5.381,0.32,0.564,0.0,0.534,Artist 1,Eladio Carrion,Nationality 1,Puerto Rico,Latin-America,56,14.0,1iyvRYYAeuJhrsxTsQW9fh,https://open.spotify.com/track/1iyvRYYAeuJhrsx...
18392,64,Si La Calle Llama - Remix,"Eladio Carrion, Myke Towers",17/03/2023,0.469,0.639,-5.381,0.32,0.564,0.0,0.534,Artist 1,Eladio Carrion,Nationality 1,Puerto Rico,Latin-America,137,68.0,3qXZqXGniqNt3PK2CBSZgM,https://open.spotify.com/track/3qXZqXGniqNt3PK...
456474,79,4th Dimension,"KIDS SEE GHOSTS, Louis Prima",08/06/2018,0.765,0.542,-6.755,0.39,0.278,0.0,0.734,Artist 1,KIDS SEE GHOSTS,Nationality 1,United States,Anglo-America,122,61.0,6JyEh4kl9DLwmSAoNDRn5b,https://open.spotify.com/track/6JyEh4kl9DLwmSA...
456520,88,Cudi Montage,KIDS SEE GHOSTS,08/06/2018,0.765,0.542,-6.755,0.39,0.278,0.0,0.734,Artist 1,KIDS SEE GHOSTS,Nationality 1,United States,Anglo-America,113,113.0,4ffyvGU97UkoUkHEOPzPZT,https://open.spotify.com/track/4ffyvGU97UkoUkH...

In [23]:
print(df.shape[0])
print(df_clean_final.shape[0])

651936
467061

In [24]:
df_clean_final.to_csv('delete_duplication.csv', index=False, sep =';')