In [195]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [196]:
df = pd.read_csv('Spotify_Dataset_V3 2.csv', delimiter=';')

In [ ]:
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5176.0,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...
1,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",29/05/2023,0.668,0.758,-5176.0,0.033,0.483,0.000,0.834,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...
2,2,WHERE SHE GOES,Bad Bunny,29/05/2023,0.652,0.800,-4019.0,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5678.0,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...
4,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",29/05/2023,0.812,0.479,-5678.0,0.333,0.213,0.000,0.559,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...

1. Drop unused column EX. Song URL

In [198]:
df.drop(['Song URL'],axis = 1, inplace = True)

2. Check Data Profile

In [199]:
df[['Danceability', 'Energy', 'Loudness', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Valence']].describe()

,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence
count,651936.000000,651936.000000,651936.000000,651936.000000,651936.000000,651936.000000,651936.000000
mean,0.697730,0.652049,-5295.645217,0.109946,0.230694,0.007647,0.523134
std,0.133186,0.155684,2785.261321,0.096841,0.230710,0.054724,0.223926
min,0.073000,0.005000,-34475.000000,0.022000,0.000000,0.000000,0.026000
25%,0.617000,0.549000,-6825.000000,0.045000,0.048000,0.000000,0.356000
50%,0.719000,0.671000,-5206.000000,0.068000,0.152000,0.000000,0.521000
75%,0.793000,0.771000,-3885.000000,0.136000,0.349000,0.000000,0.696000
max,0.985000,0.996000,1509.000000,0.966000,0.994000,0.956000,0.982000

3. We need to normalize data for loudness first

In [200]:
cleaned_df = df[(df['Loudness'] <= 0 ) & (df['Loudness'] >= -60 )] # This is 
cleaned_df

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
14,11,Classy 101,"Feid, Young Miko",29/05/2023,0.859,0.658,-4.790,0.159,0.145,0.0,0.672,Artist 1,Feid,Nationality 1,Colombia,Latin-America,190,95.0,6XSqqQIy7Lm7SnwxS4NrGx
15,11,Classy 101,"Feid, Young Miko",29/05/2023,0.859,0.658,-4.790,0.159,0.145,0.0,0.672,Artist 2,Young Miko,Nationality 2,Puerto Rico,Latin-America,190,95.0,6XSqqQIy7Lm7SnwxS4NrGx
25,17,"Angel Pt. 1 (feat. Jimin of BTS, JVKE & Muni L...","Kodak Black, NLE Choppa, Jimin, JVKE, Muni Long",29/05/2023,0.715,0.681,-4.250,0.113,0.129,0.0,0.277,Artist 1,Kodak Black,Nationality 1,United States,Anglo-America,184,36.8,1vvcEHQdaUTvWt0EIUYcFK
26,17,"Angel Pt. 1 (feat. Jimin of BTS, JVKE & Muni L...","Kodak Black, NLE Choppa, Jimin, JVKE, Muni Long",29/05/2023,0.715,0.681,-4.250,0.113,0.129,0.0,0.277,Artist 2,NLE Choppa,Nationality 2,United States,Anglo-America,184,36.8,1vvcEHQdaUTvWt0EIUYcFK
27,17,"Angel Pt. 1 (feat. Jimin of BTS, JVKE & Muni L...","Kodak Black, NLE Choppa, Jimin, JVKE, Muni Long",29/05/2023,0.715,0.681,-4.250,0.113,0.129,0.0,0.277,Artist 3,Jimin,Nationality 3,South Korea,Asia,184,36.8,1vvcEHQdaUTvWt0EIUYcFK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651848,123,Photograph,Ed Sheeran,01/01/2017,0.614,0.379,-10.480,0.048,0.607,0.0,0.201,Artist 1,Ed Sheeran,Nationality 1,United Kingdom,Europe,78,78.0,6fxVffaTuwjgEk5h9QyRjy
651875,148,Dynamite (feat. Pretty Sister),Nause,01/01/2017,0.811,0.801,-6.000,0.080,0.055,0.0,0.693,Artist 1,Nause,Nationality 1,Sweden,Europe,53,53.0,2Ae5awwKvQpTBKQHr1TYCg
651886,157,Love On The Brain,Rihanna,01/01/2017,0.509,0.637,-4.830,0.047,0.072,0.0,0.378,Artist 1,Rihanna,Nationality 1,Barbados,Anglo-America,44,44.0,2aksifNn5ph8igDOkPBA02
651887,158,Desde Esa Noche (feat. Maluma),Thalia,01/01/2017,0.780,0.929,-0.739,0.053,0.171,0.0,0.837,Artist 1,Thalia,Nationality 1,Mexico,Latin-America,43,43.0,1pWYnQIlqxTh5bxuPmTG4E
651900,170,goosebumps,Travis Scott,01/01/2017,0.841,0.728,-3.370,0.048,0.085,0.0,0.430,Artist 1,Travis Scott,Nationality 1,United States,Anglo-America,31,31.0,6gBFPUFcJLzWGx4lenP6h2

In [201]:
df['Loudness'] = np.where(
    (df['Loudness'] <= -60) | (df['Loudness'] >= 0),  # Condition: x is NOT in (-60, 0)
    df['Loudness'] / 1000,                           # Value if TRUE (divide the "others")
    df['Loudness']                                   # Value if FALSE (keep the "good" values)
)

In [202]:
df['Loudness'] = MinMaxScaler().fit_transform(df[['Loudness']])

4. Change DateTime

In [203]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [204]:
df

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,0.814223,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E
1,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,0.814223,0.033,0.483,0.000,0.834,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E
2,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,0.846376,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,0.800272,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU
4,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,0.800272,0.333,0.213,0.000,0.559,Artist 2,Peso Pluma,Nationality 2,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651931,197,Oh Lord,MiC LOWRY,2017-01-01,0.273,0.794,0.773427,0.068,0.022,0.000,0.377,Artist 1,MiC LOWRY,Nationality 1,United Kingdom,Europe,4,4.0,1sTUEdVO85YU8Ymk2jeAls
651932,198,Superstition - Single Version,Stevie Wonder,2017-01-01,0.650,0.658,0.654930,0.085,0.089,0.004,0.883,Artist 1,Stevie Wonder,Nationality 1,United States,Anglo-America,3,3.0,5lXcSvHRVjQJ3LB2rLKQog
651933,199,Secrets,The Weeknd,2017-01-01,0.665,0.771,0.797466,0.053,0.016,0.000,0.764,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,2,2.0,3DX4Y0egvc0slLcLl31h2p
651934,200,Ni**as In Paris,"JAY-Z, Kanye West",2017-01-01,0.757,0.882,0.787850,0.248,0.076,0.000,0.684,Artist 1,JAY-Z,Nationality 1,United States,Anglo-America,1,1.0,2KpCpk6HjXXLb7nnXoXA5O
651935,200,Ni**as In Paris,"JAY-Z, Kanye West",2017-01-01,0.757,0.882,0.787850,0.248,0.076,0.000,0.684,Artist 2,Kanye West,Nationality 2,United States,Anglo-America,1,1.0,2KpCpk6HjXXLb7nnXoXA5O

In [205]:
is_duplicate = df.duplicated(subset=['Rank', 'Date', 'Title'], keep='first')
duplicates = df[is_duplicate]
df.drop(duplicates.index, inplace=True)

In [206]:
df

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,0.814223,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E
2,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,0.846376,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,0.800272,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU
5,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,0.726517,0.033,0.435,0.000,0.726,Artist 1,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7
6,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,0.844792,0.047,0.228,0.000,0.562,Artist 1,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651930,196,White Iverson,Post Malone,2017-01-01,0.675,0.562,0.744692,0.035,0.233,0.000,0.309,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,5,5.0,6eT7xZZlB2mwyzJ2sUKG6w
651931,197,Oh Lord,MiC LOWRY,2017-01-01,0.273,0.794,0.773427,0.068,0.022,0.000,0.377,Artist 1,MiC LOWRY,Nationality 1,United Kingdom,Europe,4,4.0,1sTUEdVO85YU8Ymk2jeAls
651932,198,Superstition - Single Version,Stevie Wonder,2017-01-01,0.650,0.658,0.654930,0.085,0.089,0.004,0.883,Artist 1,Stevie Wonder,Nationality 1,United States,Anglo-America,3,3.0,5lXcSvHRVjQJ3LB2rLKQog
651933,199,Secrets,The Weeknd,2017-01-01,0.665,0.771,0.797466,0.053,0.016,0.000,0.764,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,2,2.0,3DX4Y0egvc0slLcLl31h2p
651934,200,Ni**as In Paris,"JAY-Z, Kanye West",2017-01-01,0.757,0.882,0.787850,0.248,0.076,0.000,0.684,Artist 1,JAY-Z,Nationality 1,United States,Anglo-America,1,1.0,2KpCpk6HjXXLb7nnXoXA5O

In [207]:
df[(df['Title'] == '美女と野獣') & (df['Date'] == '2017-04-12') & (df['Artist (Ind.)'] == 'John Legend')]

Empty DataFrame
Columns: [Rank, Title, Artists, Date, Danceability, Energy, Loudness, Speechiness, Acousticness, Instrumentalness, Valence, # of Artist, Artist (Ind.), # of Nationality, Nationality, Continent, Points (Total), Points (Ind for each Artist/Nat), id]
Index: []

In [208]:
df.value_counts(subset=['Title', 'Date', 'Artist (Ind.)'])

Title           Date        Artist (Ind.)
Take My Breath  2022-01-09  The Weeknd       2
Amorfoda        2018-02-18  Bad Bunny        2
IDOL            2018-08-30  BTS              2
                2018-08-29  BTS              2
                2018-08-28  BTS              2
                                            ..
Heather         2022-06-11  Conan Gray       1
                2022-06-09  Conan Gray       1
                2022-06-08  Conan Gray       1
                2022-06-07  Conan Gray       1
美女と野獣           2017-04-12  Ariana Grande    1
Name: count, Length: 468710, dtype: int64

In [209]:
df[(df['Title'] == "when the party's over") & (df['Date'] == '2020-12-30') & (df['Artist (Ind.)'] == 'Billie Eilish')]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
249393,188,when the party's over,Billie Eilish,2020-12-30,0.367,0.111,0.566669,0.097,0.978,0.0,0.198,Artist 1,Billie Eilish,Nationality 1,United States,Anglo-America,13,13.0,43zdsphuZLzwA9k4DJhU0I

In [ ]:
df.drop_duplicates(subset=['Title', 'Date','Artist (Ind.)'], keep='first')

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,0.814223,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E
2,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,0.846376,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,0.800272,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU
5,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,0.726517,0.033,0.435,0.000,0.726,Artist 1,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7
6,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,0.844792,0.047,0.228,0.000,0.562,Artist 1,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651930,196,White Iverson,Post Malone,2017-01-01,0.675,0.562,0.744692,0.035,0.233,0.000,0.309,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,5,5.0,6eT7xZZlB2mwyzJ2sUKG6w
651931,197,Oh Lord,MiC LOWRY,2017-01-01,0.273,0.794,0.773427,0.068,0.022,0.000,0.377,Artist 1,MiC LOWRY,Nationality 1,United Kingdom,Europe,4,4.0,1sTUEdVO85YU8Ymk2jeAls
651932,198,Superstition - Single Version,Stevie Wonder,2017-01-01,0.650,0.658,0.654930,0.085,0.089,0.004,0.883,Artist 1,Stevie Wonder,Nationality 1,United States,Anglo-America,3,3.0,5lXcSvHRVjQJ3LB2rLKQog
651933,199,Secrets,The Weeknd,2017-01-01,0.665,0.771,0.797466,0.053,0.016,0.000,0.764,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,2,2.0,3DX4Y0egvc0slLcLl31h2p
651934,200,Ni**as In Paris,"JAY-Z, Kanye West",2017-01-01,0.757,0.882,0.787850,0.248,0.076,0.000,0.684,Artist 1,JAY-Z,Nationality 1,United States,Anglo-America,1,1.0,2KpCpk6HjXXLb7nnXoXA5O

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,0.814223,0.033,0.483,0.000,0.834,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E
2,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,0.846376,0.061,0.143,0.629,0.234,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1
3,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,0.800272,0.333,0.213,0.000,0.559,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU
5,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,0.726517,0.033,0.435,0.000,0.726,Artist 1,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7
6,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,0.844792,0.047,0.228,0.000,0.562,Artist 1,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651930,196,White Iverson,Post Malone,2017-01-01,0.675,0.562,0.744692,0.035,0.233,0.000,0.309,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,5,5.0,6eT7xZZlB2mwyzJ2sUKG6w
651931,197,Oh Lord,MiC LOWRY,2017-01-01,0.273,0.794,0.773427,0.068,0.022,0.000,0.377,Artist 1,MiC LOWRY,Nationality 1,United Kingdom,Europe,4,4.0,1sTUEdVO85YU8Ymk2jeAls
651932,198,Superstition - Single Version,Stevie Wonder,2017-01-01,0.650,0.658,0.654930,0.085,0.089,0.004,0.883,Artist 1,Stevie Wonder,Nationality 1,United States,Anglo-America,3,3.0,5lXcSvHRVjQJ3LB2rLKQog
651933,199,Secrets,The Weeknd,2017-01-01,0.665,0.771,0.797466,0.053,0.016,0.000,0.764,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,2,2.0,3DX4Y0egvc0slLcLl31h2p
651934,200,Ni**as In Paris,"JAY-Z, Kanye West",2017-01-01,0.757,0.882,0.787850,0.248,0.076,0.000,0.684,Artist 1,JAY-Z,Nationality 1,United States,Anglo-America,1,1.0,2KpCpk6HjXXLb7nnXoXA5O

In [214]:
df[df['id'] == '6Knv6wdA0luoMUuuoYi2i1']

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,Valence,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id
651547,194,My House,Flo Rida,2017-01-02,0.688,0.702,0.824894,0.05,0.022,0.0,0.74,Artist 1,Flo Rida,Nationality 1,United States,Anglo-America,7,7.0,6Knv6wdA0luoMUuuoYi2i1
651890,161,My House,Flo Rida,2017-01-01,0.688,0.702,0.824894,0.05,0.022,0.0,0.74,Artist 1,Flo Rida,Nationality 1,United States,Anglo-America,40,40.0,6Knv6wdA0luoMUuuoYi2i1