In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('final_cleaned_data.csv', sep = ';')
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,-5.176,0.033,0.483,0.000,...,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...,0.849862
1,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,-4.019,0.061,0.143,0.629,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...,0.883423
2,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,-5.678,0.333,0.213,0.000,...,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...,0.835301
3,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,-8.332,0.033,0.435,0.000,...,Artist 1,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7,https://open.spotify.com/track/7FbrGaHYVDmfr7K...,0.758318
4,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,-4.076,0.047,0.228,0.000,...,Artist 1,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK,https://open.spotify.com/track/6pD0ufEQq0xdHSs...,0.881769

In [5]:
df.shape

(467061, 21)

In [8]:
df['Date'] = pd.to_datetime(df['Date'])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467061 entries, 0 to 467060
Data columns (total 21 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Rank                              467061 non-null  int64
 1   Title                             467061 non-null  object
 2   Artists                           467061 non-null  object
 3   Date                              467061 non-null  datetime64[ns]
 4   Danceability                      467061 non-null  float64
 5   Energy                            467061 non-null  float64
 6   Loudness                          467061 non-null  float64
 7   Speechiness                       467061 non-null  float64
 8   Acousticness                      467061 non-null  float64
 9   Instrumentalness                  467061 non-null  float64
 10  Valence                           467061 non-null  float64
 11  # of Artist                       467061 non-null  object
 12  Artist (Ind.)                     467061 non-null  object
 13  # of Nationality                  467061 non-null  object
 14  Nationality                       467061 non-null  object
 15  Continent                         467061 non-null  object
 16  Points (Total)                    467061 non-null  int64
 17  Points (Ind for each Artist/Nat)  467061 non-null  float64
 18  id                                467061 non-null  object
 19  Song URL                          467061 non-null  object
 20  Loudness_norm                     467061 non-null  float64
dtypes: datetime64[ns](1), float64(9), int64(2), object(9)
memory usage: 74.8+ MB

In [ ]:
song_release_dates = df.groupby('id')['Date'].min()

In [13]:
df['first_appearance'] = df['id'].map(song_release_dates)

In [14]:
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm,first_appearance
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,-5.176,0.033,0.483,0.000,...,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...,0.849862,2023-04-28
1,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,-4.019,0.061,0.143,0.629,...,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...,0.883423,2023-05-19
2,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,-5.678,0.333,0.213,0.000,...,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...,0.835301,2023-03-18
3,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,-8.332,0.033,0.435,0.000,...,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7,https://open.spotify.com/track/7FbrGaHYVDmfr7K...,0.758318,2023-04-01
4,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,-4.076,0.047,0.228,0.000,...,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK,https://open.spotify.com/track/6pD0ufEQq0xdHSs...,0.881769,2023-04-17

### Split train validation and test

In [15]:
release_year = song_release_dates.dt.year

def assign_split(year):
    if 2017 <= year <= 2020:
        return 'train'
    elif year == 2021:
        return 'val'
    elif 2022 <= year <= 2023:
        return 'test'
    else:
        return 'ignore' 

split_labels = release_year.apply(assign_split)


df['split'] = df['id'].map(split_labels)

In [18]:
df['split'].value_counts()

split
train    345628
val       61539
test      59894
Name: count, dtype: int64

In [19]:
train_start, train_end = '2017-01-01', '2020-12-31'
val_start, val_end     = '2021-01-01', '2021-12-31'
test_start, test_end   = '2022-01-01', '2023-12-31'


train_song_ids = song_release_dates[
    (song_release_dates >= train_start) & (song_release_dates <= train_end)
].index

val_song_ids = song_release_dates[
    (song_release_dates >= val_start) & (song_release_dates <= val_end)
].index

test_song_ids = song_release_dates[
    (song_release_dates >= test_start) & (song_release_dates <= test_end)
].index

In [20]:
train_df = df[df['id'].isin(train_song_ids)]
val_df   = df[df['id'].isin(val_song_ids)]
test_df  = df[df['id'].isin(test_song_ids)]

In [31]:
train_df['first_appearance'].describe()

count                           345628
mean     2018-09-30 21:16:41.293876736
min                2017-01-01 00:00:00
25%                2017-08-25 00:00:00
50%                2018-08-28 00:00:00
75%                2019-10-18 00:00:00
max                2020-12-31 00:00:00
Name: first_appearance, dtype: object

In [21]:
len(train_df), len(val_df), len(test_df)

(345628, 61539, 59894)

### Aggregation

In [24]:
song_perf_train = train_df.groupby('id').agg({
    'Rank': ['min', 'mean', 'count'],
    'Date': ['min', 'max'],
    'Title': 'first',
    'Artist (Ind.)': 'first'
}).reset_index()

song_perf_train.columns = ['id', 'best_rank', 'avg_rank', 'total_weeks_charted',
                            'first_appearance', 'last_appearance', 'Title', 'Artist']

In [25]:
song_perf_train.shape

(6158, 8)

In [32]:
print(f"  Unique songs: {len(song_perf_train):,}")
print(f"  Date range: {song_perf_train['first_appearance'].min().date()} to "
      f"{song_perf_train['first_appearance'].max().date()}")

  Unique songs: 6,158
  Date range: 2017-01-01 to 2020-12-31

In [33]:
song_perf_val = val_df.groupby('id').agg({
    'Rank': ['min', 'mean', 'count'],
    'Date': ['min', 'max'],
    'Title': 'first',
    'Artist (Ind.)': 'first'
}).reset_index()

song_perf_val.columns = ['id', 'best_rank', 'avg_rank', 'total_weeks_charted',
                           'first_appearance', 'last_appearance', 'Title', 'Artist']
song_perf_val.shape

(1414, 8)

In [34]:
song_perf_test = test_df.groupby('id').agg({
    'Rank': ['min', 'mean', 'count'],
    'Date': ['min', 'max'],
    'Title': 'first',
    'Artist (Ind.)': 'first'
}).reset_index()

song_perf_test.columns = ['id', 'best_rank', 'avg_rank', 'total_weeks_charted',
                           'first_appearance', 'last_appearance', 'Title', 'Artist']
song_perf_test.shape

(1589, 8)

### Check overlap

In [ ]:

train_ids = set(song_perf_train['id'])
val_ids   = set(song_perf_val['id'])
test_ids  = set(song_perf_test['id'])


overlap_train_val  = train_ids & val_ids
overlap_train_test = train_ids & test_ids
overlap_val_test   = val_ids & test_ids
        
print("train ∩ val:", len(overlap_train_val))
print("train ∩ test:", len(overlap_train_test))
print("val ∩ test:", len(overlap_val_test))

train ∩ val: 0
train ∩ test: 0
val ∩ test: 0

### Label popularity
- train

In [52]:
song_perf_train['peak_score'] = (201 - song_perf_train['best_rank']) / 200 * 100

# Calculate longevity score (cap at 20 weeks)
song_perf_train['longevity_score'] = np.minimum(song_perf_train['total_weeks_charted'] / 20, 1.0) * 100

# Calculate popularity score (weighted combination)
weight_peak = 0.4
weight_longevity = 0.6
song_perf_train['popularity_score'] = (
    weight_peak * song_perf_train['peak_score'] + 
    weight_longevity * song_perf_train['longevity_score']
)

train_threshold = song_perf_train['popularity_score'].quantile(0.7)
song_perf_train['popularity_label'] = song_perf_train['popularity_score'].apply(
    lambda x: 'Popular' if x >= train_threshold else 'Not Popular'
)
print(train_threshold)

83.77999999999993

- validation

In [49]:
song_perf_val['peak_score'] = (201 - song_perf_val['best_rank']) / 200 * 100

# Calculate longevity score (cap at 20 weeks)
song_perf_val['longevity_score'] = np.minimum(song_perf_val['total_weeks_charted'] / 20, 1.0) * 100


# Calculate popularity score (weighted combination)
weight_peak = 0.4
weight_longevity = 0.6
song_perf_val['popularity_score'] = (
    weight_peak * song_perf_val['peak_score'] + 
    weight_longevity * song_perf_val['longevity_score']
)
train_threshold = song_perf_train['popularity_score'].quantile(0.7)
song_perf_val['popularity_label'] = song_perf_val['popularity_score'].apply(
    lambda x: 'Popular' if x >= train_threshold else 'Not Popular'
)

- test

In [50]:
song_perf_test['peak_score'] = (201 - song_perf_test['best_rank']) / 200 * 100

# Calculate longevity score (cap at 20 weeks)
song_perf_test['longevity_score'] = np.minimum(song_perf_test['total_weeks_charted'] / 20, 1.0) * 100

# Calculate popularity score (weighted combination)
weight_peak = 0.4
weight_longevity = 0.6
song_perf_test['popularity_score'] = (
    weight_peak * song_perf_test['peak_score'] + 
    weight_longevity * song_perf_test['longevity_score']
)

train_threshold = song_perf_train['popularity_score'].quantile(0.7)
song_perf_test['popularity_label'] = song_perf_train['popularity_score'].apply(
    lambda x: 'Popular' if x >= train_threshold else 'Not Popular'
)

In [43]:
song_perf_test.head()

,id,best_rank,avg_rank,total_weeks_charted,first_appearance,last_appearance,Title,Artist,peak_score,longevity_score,popularity_score,popularity_label
0,00Ga884hbpVvCNyeQdle1U,99,149.000000,2,2023-03-10,2023-03-11,Violet Chemistry,Miley Cyrus,51.0,10.0,26.4,Popular
1,00I41xsW6SunZDJ5fB8KAd,65,65.000000,1,2022-07-15,2022-07-15,Safety Zone,j-hope,68.0,5.0,30.2,Not Popular
2,00imgaPlYRrMGn9o83hfmk,44,111.666667,3,2022-07-08,2022-07-10,LOOSE CHANGE,Brent Faiyaz,78.5,15.0,40.4,Popular
3,01VzuxoBYMAJLObfU0w6dI,195,195.000000,1,2022-07-08,2022-07-08,ADDICTIONS (FEAT. Tre' Amani),Brent Faiyaz,3.0,5.0,4.2,Not Popular
4,01kfSdF9zfcDLri5sSWEoL,173,183.500000,4,2022-09-10,2022-09-18,RAVE,Dxrk ãƒ€ãƒ¼ã‚¯,14.0,20.0,17.6,Not Popular

In [44]:
song_perf_train.head()

,id,best_rank,avg_rank,total_weeks_charted,first_appearance,last_appearance,Title,Artist,peak_score,longevity_score,popularity_score,popularity_label
0,000xQL6tZNLJzIrtIgxqSl,40,101.500000,118,2017-03-24,2017-09-12,Still Got Time (feat. PARTYNEXTDOOR),ZAYN,80.5,100.0,98.8,Popular
1,003VDDA7J3Xb2ZFlNx7nIZ,108,138.000000,2,2020-02-07,2020-02-08,YELL OH,Trippie Redd,46.5,10.0,6.4,Not Popular
2,003eoIwxETJujVWmNFMoZy,91,136.500000,14,2018-06-15,2018-06-28,Growing Pains,Alessia Cara,55.0,70.0,84.2,Popular
3,003vvx7Niy0yvhvHt4a68B,73,168.069643,560,2020-08-15,2023-01-01,Mr. Brightside,The Killers,64.0,100.0,30.4,Not Popular
4,00B7TZ0Xawar6NZ00JFomN,61,109.285714,14,2018-04-06,2018-04-19,Best Life (feat. Chance The Rapper),Cardi B,70.0,70.0,19.0,Not Popular

In [45]:
song_perf_val.head()

,id,best_rank,avg_rank,total_weeks_charted,first_appearance,last_appearance,Title,Artist,peak_score,longevity_score,popularity_score,popularity_label
0,00Blm7zeNqgYLPtW6zg8cj,7,70.861905,210,2021-11-05,2022-06-02,One Right Now (with The Weeknd),Post Malone,97.0,100.0,98.8,Popular
1,01BCvCKQNDmFQQQSjrzPnm,184,184.000000,1,2021-10-01,2021-10-01,GHIGLIOTTI - feat. Noyz rcos,Salmo,8.5,5.0,6.4,Not Popular
2,01K4zKU104LyJ8gMb7227B,20,79.187500,16,2021-11-12,2021-11-30,Nothing New (feat. Phoebe Bridgers) (Taylor's ...,Taylor Swift,90.5,80.0,84.2,Popular
3,01QdEx6kFr78ZejhQtWR5m,79,123.500000,2,2021-04-09,2021-04-10,Forever & Always (Piano Version) (Taylor's Ver...,Taylor Swift,61.0,10.0,30.4,Not Popular
4,01QhKtUc12FGw2wX7dMYvv,121,121.000000,1,2021-09-24,2021-09-24,LOCO - English Ver.,ITZY,40.0,5.0,19.0,Not Popular

In [ ]:
print(f"\n  TRAINING LABELS (2017-2020):")
train_label_counts = song_perf_train['popularity_label'].value_counts()
print(f"  Popular:     {train_label_counts.get('Popular', 0):,} "
      f"({train_label_counts.get('Popular', 0)/len(song_perf_train)*100:.1f}%)")
print(f"  Not Popular: {train_label_counts.get('Not Popular', 0):,} "
      f"({train_label_counts.get('Not Popular', 0)/len(song_perf_train)*100:.1f}%)")

print(f"\n VALIDATION LABELS (2021-2023):")
val_label_counts = song_perf_val['popularity_label'].value_counts()
print(f"  Popular:     {val_label_counts.get('Popular', 0):,} "
      f"({val_label_counts.get('Popular', 0)/len(song_perf_val)*100:.1f}%)")
print(f"  Not Popular: {val_label_counts.get('Not Popular', 0):,} "
      f"({val_label_counts.get('Not Popular', 0)/len(song_perf_val)*100:.1f}%)")

print(f"\n TEST LABELS (2022-2023):")
test_label_counts = song_perf_test['popularity_label'].value_counts()
print(f"  Popular:     {test_label_counts.get('Popular', 0):,} "
      f"({test_label_counts.get('Popular', 0)/len(song_perf_test)*100:.1f}%)")
print(f"  Not Popular: {test_label_counts.get('Not Popular', 0):,} "
      f"({test_label_counts.get('Not Popular', 0)/len(song_perf_test)*100:.1f}%)")

  TRAINING LABELS (2017-2021):
  Popular:     1,848 (30.0%)
  Not Popular: 4,310 (70.0%)

 VALIDATION LABELS (2022-2023):
  Popular:     399 (28.2%)
  Not Popular: 1,015 (71.8%)

 TEST LABELS (2022-2023):
  Popular:     449 (28.3%)
  Not Popular: 1,140 (71.7%)

In [54]:
song_perf_train['split'] = 'train'
song_perf_val['split']   = 'val'
song_perf_test['split'] = 'test'


songs_labeled = pd.concat(
    [song_perf_train, song_perf_val, song_perf_test],
    ignore_index=True
)

### Save aggregate dataset

In [ ]:
output_file = 'aggregated_dataset.csv'
songs_labeled.to_csv(output_file, index=False, sep=';')
print(f" Saved to: {output_file}")
print(f"  Shape: {songs_labeled.shape}")

 Saved to: aggregate_dataset.csv
  Shape: (9161, 13)

### Save raw dataset

In [67]:
df['split'].value_counts()

split
train    345628
val       61539
test      59894
Name: count, dtype: int64

In [68]:
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm,first_appearance,split
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,-5.176,0.033,0.483,0.000,...,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...,0.849862,2023-04-28,test
1,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,-4.019,0.061,0.143,0.629,...,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...,0.883423,2023-05-19,test
2,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,-5.678,0.333,0.213,0.000,...,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...,0.835301,2023-03-18,test
3,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,-8.332,0.033,0.435,0.000,...,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7,https://open.spotify.com/track/7FbrGaHYVDmfr7K...,0.758318,2023-04-01,test
4,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,-4.076,0.047,0.228,0.000,...,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK,https://open.spotify.com/track/6pD0ufEQq0xdHSs...,0.881769,2023-04-17,test

### Save split cleaned dataset

In [70]:
output_file = 'split_cleaned_dataset.csv'
df.to_csv(output_file, index=False, sep=';')
print(f" Saved to: {output_file}")
print(f" Shape: {df.shape}")

 Saved to: split_cleaned_dataset.csv
 Shape: (467061, 23)